-- HMSI Supabase schema
-- Run this once in the Supabase SQL editor before enabling submissions.

create extension if not exists pgcrypto;

create table if not exists public.fundraisers (
  id text primary key,
  title varchar(160) not null,
  description text not null,
  category text not null check (category in ('medical', 'education', 'housing', 'emergency')),
  target_amount numeric(14, 2) not null check (target_amount > 0),
  raised_amount numeric(14, 2) not null default 0 check (raised_amount >= 0),
  image_url text not null,
  image_path text,
  status text not null default 'active' check (status in ('active', 'pending', 'archived', 'completed')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists fundraisers_status_created_at_idx
  on public.fundraisers (status, created_at desc);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name varchar(160) not null,
  email varchar(320) not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'resolved')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.signup_requests (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  email varchar(320) not null,
  phone varchar(64),
  message text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.fundraisers enable row level security;
alter table public.contact_messages enable row level security;
alter table public.signup_requests enable row level security;

drop policy if exists "Anyone can view active fundraisers" on public.fundraisers;
create policy "Anyone can view active fundraisers"
  on public.fundraisers for select
  using (status = 'active');

-- Inserts and updates are intentionally service-role-only through the server API.

drop policy if exists "Public can read fundraiser images" on storage.objects;
create policy "Public can read fundraiser images"
  on storage.objects for select
  using (bucket_id = 'fundraiser-images');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fundraiser-images',
  'fundraiser-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into public.fundraisers (id, title, description, category, target_amount, raised_amount, image_url, status, created_at)
values
  ('f1', 'Emergency Medical Surgery for Baby Tobi', 'Baby Tobi needs urgent heart surgery. Every donation counts.', 'medical', 2500000, 750000, '/images/outreach-2.png', 'active', '2026-08-01T10:00:00Z'),
  ('f2', 'Rebuilding Makoko Primary School', 'Help us fix the roof and provide desks for 200 students.', 'education', 5000000, 1200000, '/images/outreach-5.png', 'active', '2026-08-10T14:30:00Z')
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  target_amount = excluded.target_amount,
  raised_amount = excluded.raised_amount,
  image_url = excluded.image_url,
  status = excluded.status,
  updated_at = timezone('utc', now());


-- Admin workflow tables
create table if not exists public.volunteer_applications (
  id uuid primary key default gen_random_uuid(),
  name varchar(160) not null,
  email varchar(320) not null,
  phone varchar(64) not null,
  interest varchar(160) not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  account_status text not null default 'active' check (account_status in ('active', 'banned')),
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workers (
  id uuid primary key default gen_random_uuid(),
  name varchar(160) not null,
  email varchar(320) not null unique,
  phone varchar(64) not null,
  role text not null default 'worker' check (role in ('worker', 'coordinator')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.work_assignments (
  id uuid primary key default gen_random_uuid(),
  title varchar(200) not null,
  description text not null,
  kind text not null check (kind in ('assistance', 'job')),
  status text not null default 'assigned' check (status in ('assigned', 'in_progress', 'completed')),
  assigned_worker_id uuid not null references public.workers(id) on delete restrict,
  fundraiser_id text references public.fundraisers(id) on delete set null,
  due_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists volunteer_applications_status_created_at_idx
  on public.volunteer_applications (status, created_at desc);
create index if not exists work_assignments_worker_status_idx
  on public.work_assignments (assigned_worker_id, status);

-- Additive cross-role onboarding fields and one-email application register.
alter table public.volunteer_applications add column if not exists location varchar(160);
alter table public.workers add column if not exists location varchar(160);
alter table public.hmsi_member_applications add column if not exists location varchar(160);
alter table public.hmsi_members add column if not exists location varchar(160);

create table if not exists public.application_email_registry (
  id uuid primary key default gen_random_uuid(),
  email varchar(320) not null unique check (email = lower(email)),
  applicant_role text not null check (applicant_role in ('volunteer', 'worker', 'member')),
  source_table text not null check (source_table in ('volunteer_applications', 'hmsi_member_applications', 'workers', 'hmsi_members')),
  source_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
alter table public.application_email_registry enable row level security;

alter table public.volunteer_applications enable row level security;
alter table public.workers enable row level security;
alter table public.work_assignments enable row level security;

-- The server admin API uses the service-role key. No anonymous write policy is granted.
-- Public fundraiser visibility remains limited to active records.
alter table public.fundraisers drop constraint if exists fundraisers_status_check;
alter table public.fundraisers add constraint fundraisers_status_check
  check (status in ('active', 'pending', 'archived', 'rejected', 'completed'));


-- Public submission policies. New records are constrained to review-safe statuses;
-- admin-only updates, approvals, workers, and assignments remain service-role-only.
drop policy if exists "Public can submit pending fundraisers" on public.fundraisers;
create policy "Public can submit pending fundraisers"
  on public.fundraisers for insert
  with check (status = 'pending' and raised_amount = 0);

drop policy if exists "Public can submit contact messages" on public.contact_messages;
create policy "Public can submit contact messages"
  on public.contact_messages for insert
  with check (status = 'new');

drop policy if exists "Public can submit signup requests" on public.signup_requests;
create policy "Public can submit signup requests"
  on public.signup_requests for insert
  with check (true);

drop policy if exists "Public can submit volunteer applications" on public.volunteer_applications;
create policy "Public can submit volunteer applications"
  on public.volunteer_applications for insert
  with check (status = 'pending');


-- Role-aware applications, opportunities, and collaboration rooms
alter table public.volunteer_applications add column if not exists applicant_role text not null default 'volunteer';
alter table public.volunteer_applications add column if not exists account_status text not null default 'active';
alter table public.volunteer_applications drop constraint if exists volunteer_applications_account_status_check;
alter table public.volunteer_applications add constraint volunteer_applications_account_status_check
  check (account_status in ('active', 'banned'));
alter table public.volunteer_applications drop constraint if exists volunteer_applications_applicant_role_check;
alter table public.volunteer_applications add constraint volunteer_applications_applicant_role_check
  check (applicant_role in ('volunteer', 'worker'));

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  title varchar(200) not null,
  description text not null,
  audience text not null default 'volunteer' check (audience in ('volunteer', 'worker', 'both')),
  location varchar(200) not null default 'Nigeria and Africa',
  image_url text,
  image_path text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'open' check (status in ('draft', 'open', 'closed')),
  created_by varchar(320),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.opportunity_applications (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities(id) on delete cascade,
  applicant_name varchar(160) not null,
  applicant_email varchar(320) not null,
  applicant_phone varchar(64) not null,
  applicant_role text not null check (applicant_role in ('volunteer', 'worker')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  unique (opportunity_id, applicant_email)
);

create table if not exists public.community_posts (
  id uuid primary key default gen_random_uuid(),
  audience text not null default 'volunteer' check (audience in ('volunteer', 'worker', 'all')),
  author_name varchar(160) not null,
  author_role text not null check (author_role in ('volunteer', 'worker', 'admin')),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.community_posts(id) on delete cascade,
  author_name varchar(160) not null,
  author_role text not null check (author_role in ('volunteer', 'worker', 'admin')),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_likes (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.community_posts(id) on delete cascade,
  actor_key varchar(320) not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (post_id, actor_key)
);

create table if not exists public.community_comment_flags (
  id uuid primary key default gen_random_uuid(),
  comment_id uuid not null references public.community_comments(id) on delete cascade,
  post_id uuid not null references public.community_posts(id) on delete cascade,
  reporter_email varchar(320) not null,
  reporter_role text not null check (reporter_role in ('worker', 'admin')),
  reason varchar(500) not null,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  reviewed_by varchar(320),
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  unique (comment_id, reporter_email)
);

create index if not exists opportunities_status_starts_at_idx on public.opportunities (status, starts_at);
create index if not exists opportunity_applications_status_created_at_idx on public.opportunity_applications (status, created_at desc);
create index if not exists community_posts_audience_created_at_idx on public.community_posts (audience, created_at desc);
create index if not exists community_comments_post_created_at_idx on public.community_comments (post_id, created_at);
create index if not exists community_likes_post_idx on public.community_likes (post_id);
create index if not exists community_comment_flags_status_created_idx on public.community_comment_flags (status, created_at desc);
create index if not exists community_comment_flags_comment_idx on public.community_comment_flags (comment_id);

alter table public.opportunities enable row level security;
alter table public.opportunity_applications enable row level security;
alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_likes enable row level security;
alter table public.community_comment_flags enable row level security;

drop policy if exists "Public can view open opportunities" on public.opportunities;
create policy "Public can view open opportunities" on public.opportunities for select using (status = 'open');

drop policy if exists "Public can submit opportunity applications" on public.opportunity_applications;
create policy "Public can submit opportunity applications" on public.opportunity_applications for insert with check (status = 'pending');

drop policy if exists "Public can view collaboration posts" on public.community_posts;
create policy "Public can view collaboration posts" on public.community_posts for select using (true);

drop policy if exists "Public can create collaboration posts" on public.community_posts;
create policy "Public can create collaboration posts" on public.community_posts for insert with check (audience in ('volunteer', 'worker', 'all'));

drop policy if exists "Public can view collaboration comments" on public.community_comments;
create policy "Public can view collaboration comments" on public.community_comments for select using (true);

drop policy if exists "Public can create collaboration comments" on public.community_comments;
create policy "Public can create collaboration comments" on public.community_comments for insert with check (true);

drop policy if exists "Public can view collaboration likes" on public.community_likes;
create policy "Public can view collaboration likes" on public.community_likes for select using (true);

drop policy if exists "Public can create collaboration likes" on public.community_likes;
create policy "Public can create collaboration likes" on public.community_likes for insert with check (true);

drop policy if exists "Public can remove collaboration likes" on public.community_likes;
create policy "Public can remove collaboration likes"
  on public.community_likes for delete using (true);

drop policy if exists "Service role can manage community comment flags" on public.community_comment_flags;
create policy "Service role can manage community comment flags"
  on public.community_comment_flags for all to service_role using (true) with check (true);


-- Paystack donations ledger. Client payments are recorded only after server-side verification.
create table if not exists public.donations (
  id uuid primary key default gen_random_uuid(),
  fundraiser_id text references public.fundraisers(id) on delete set null,
  donor_name varchar(160) not null,
  donor_email varchar(320) not null,
  amount_ngn numeric(14, 2) not null check (amount_ngn > 0),
  paystack_reference varchar(120) not null unique,
  status text not null default 'success' check (status in ('success', 'failed', 'pending', 'reversed')),
  currency varchar(8) not null default 'NGN',
  channel varchar(40),
  paid_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists donations_created_at_idx
  on public.donations (created_at desc);
create index if not exists donations_fundraiser_id_idx
  on public.donations (fundraiser_id, created_at desc);
create index if not exists donations_status_created_at_idx
  on public.donations (status, created_at desc);

alter table public.donations enable row level security;

drop policy if exists "Service role can insert donations" on public.donations;
create policy "Service role can insert donations"
  on public.donations for insert to service_role
  with check (true);

drop policy if exists "Service role can select donations" on public.donations;
create policy "Service role can select donations"
  on public.donations for select to service_role
  using (true);

-- Donation updates and deletes remain service-role-only through the server API.


create or replace function public.increment_fundraiser_raised_amount(p_fundraiser_id text, p_amount numeric)
returns void
language sql
security definer
set search_path = public
as $$
  update public.fundraisers
  set raised_amount = raised_amount + p_amount,
      updated_at = timezone('utc', now())
  where id = p_fundraiser_id;
$$;

revoke all on function public.increment_fundraiser_raised_amount(text, numeric) from public, anon, authenticated;
grant execute on function public.increment_fundraiser_raised_amount(text, numeric) to service_role;


-- Contact message threads, dashboard notifications, and internal replies.
create table if not exists public.contact_message_replies (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.contact_messages(id) on delete cascade,
  author_name varchar(160) not null,
  author_email varchar(320),
  author_role text not null check (author_role in ('admin', 'worker')),
  body text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.contact_message_notifications (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.contact_messages(id) on delete cascade,
  recipient_email varchar(320) not null,
  recipient_role text not null check (recipient_role in ('admin', 'worker')),
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  read_at timestamptz,
  unique (message_id, recipient_email)
);

create index if not exists contact_message_replies_message_created_idx
  on public.contact_message_replies (message_id, created_at);
create index if not exists contact_message_notifications_recipient_read_idx
  on public.contact_message_notifications (recipient_email, is_read, created_at desc);

alter table public.contact_message_replies enable row level security;
alter table public.contact_message_notifications enable row level security;

-- Dashboard APIs use the service-role key after validating admin/worker identity.
drop policy if exists "Service role can manage contact replies" on public.contact_message_replies;
create policy "Service role can manage contact replies"
  on public.contact_message_replies for all to service_role
  using (true) with check (true);

drop policy if exists "Service role can manage contact notifications" on public.contact_message_notifications;
create policy "Service role can manage contact notifications"
  on public.contact_message_notifications for all to service_role
  using (true) with check (true);


-- Newsletter subscribers, role-based drafts, approvals, and delivery history.
create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email varchar(320) not null unique,
  unsubscribe_token uuid not null default gen_random_uuid() unique,
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  subscribed_at timestamptz not null default timezone('utc', now()),
  unsubscribed_at timestamptz
);

create table if not exists public.newsletter_drafts (
  id uuid primary key default gen_random_uuid(),
  title varchar(240) not null,
  subject varchar(240) not null,
  body text not null,
  image_url text,
  image_path text,
  author_name varchar(160) not null,
  author_email varchar(320) not null,
  author_role text not null check (author_role in ('admin', 'worker', 'volunteer')),
  status text not null default 'draft' check (status in ('draft', 'pending_worker_approval', 'pending_admin_approval', 'approved', 'rejected', 'sent')),
  worker_approved_by varchar(320),
  worker_approved_at timestamptz,
  admin_approved_by varchar(320),
  admin_approved_at timestamptz,
  rejection_reason text,
  sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.newsletter_approval_events (
  id uuid primary key default gen_random_uuid(),
  newsletter_id uuid not null references public.newsletter_drafts(id) on delete cascade,
  actor_name varchar(160) not null,
  actor_email varchar(320) not null,
  actor_role text not null check (actor_role in ('admin', 'worker', 'volunteer')),
  action text not null check (action in ('submitted', 'worker_approved', 'admin_approved', 'rejected', 'sent')),
  note text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.newsletter_delivery_logs (
  id uuid primary key default gen_random_uuid(),
  newsletter_id uuid not null references public.newsletter_drafts(id) on delete cascade,
  subscriber_email varchar(320) not null,
  provider text not null default 'resend',
  provider_message_id varchar(240),
  status text not null check (status in ('sent', 'failed')),
  error_message text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists newsletter_drafts_status_created_idx
  on public.newsletter_drafts (status, created_at desc);
create index if not exists newsletter_approval_events_newsletter_created_idx
  on public.newsletter_approval_events (newsletter_id, created_at);
create index if not exists newsletter_delivery_logs_newsletter_created_idx
  on public.newsletter_delivery_logs (newsletter_id, created_at);

alter table public.newsletter_subscribers enable row level security;
alter table public.newsletter_drafts enable row level security;
alter table public.newsletter_approval_events enable row level security;
alter table public.newsletter_delivery_logs enable row level security;

drop policy if exists "Service role can manage newsletter subscribers" on public.newsletter_subscribers;
create policy "Service role can manage newsletter subscribers"
  on public.newsletter_subscribers for all to service_role
  using (true) with check (true);

drop policy if exists "Service role can manage newsletter drafts" on public.newsletter_drafts;
create policy "Service role can manage newsletter drafts"
  on public.newsletter_drafts for all to service_role
  using (true) with check (true);

drop policy if exists "Service role can manage newsletter approval events" on public.newsletter_approval_events;
create policy "Service role can manage newsletter approval events"
  on public.newsletter_approval_events for all to service_role
  using (true) with check (true);

drop policy if exists "Service role can manage newsletter delivery logs" on public.newsletter_delivery_logs;
create policy "Service role can manage newsletter delivery logs"
  on public.newsletter_delivery_logs for all to service_role
  using (true) with check (true);


-- Featured homepage stories submitted by approved workers/volunteers or published directly by admins.
create table if not exists public.featured_story_drafts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  excerpt text not null,
  body text not null,
  category text not null default 'HMSI field story',
  image_url text,
  author_name text not null,
  author_email text not null,
  author_role text not null check (author_role in ('admin', 'worker', 'volunteer')),
  status text not null default 'pending_admin_approval' check (status in ('draft', 'pending_admin_approval', 'approved', 'rejected', 'published')),
  rejection_reason text,
  approved_by text,
  approved_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.featured_story_approval_events (
  id uuid primary key default gen_random_uuid(),
  story_id uuid not null references public.featured_story_drafts(id) on delete cascade,
  action text not null check (action in ('submitted', 'approved', 'rejected', 'published', 'deleted')),
  actor_email text not null,
  actor_role text not null check (actor_role in ('admin', 'worker', 'volunteer')),
  reason text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists featured_story_drafts_status_published_idx
  on public.featured_story_drafts (status, published_at desc);
create index if not exists featured_story_drafts_author_created_idx
  on public.featured_story_drafts (author_email, created_at desc);
create index if not exists featured_story_approval_events_story_created_idx
  on public.featured_story_approval_events (story_id, created_at desc);

alter table public.featured_story_drafts enable row level security;
alter table public.featured_story_approval_events enable row level security;

drop policy if exists "Service role can manage featured story drafts" on public.featured_story_drafts;
create policy "Service role can manage featured story drafts"
  on public.featured_story_drafts for all to service_role using (true) with check (true);

drop policy if exists "Service role can manage featured story approval events" on public.featured_story_approval_events;
create policy "Service role can manage featured story approval events"
  on public.featured_story_approval_events for all to service_role using (true) with check (true);

create or replace function public.touch_featured_story_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists featured_story_drafts_updated_at on public.featured_story_drafts;
create trigger featured_story_drafts_updated_at
before update on public.featured_story_drafts
for each row execute function public.touch_featured_story_updated_at();


-- HMSI newsroom articles submitted by approved team members or published directly by admins.
create table if not exists public.news_articles (
  id uuid primary key default gen_random_uuid(),
  headline varchar(220) not null,
  summary text not null,
  body text not null,
  category varchar(100) not null default 'HMSI news',
  image_url text,
  author_name varchar(160) not null,
  author_email varchar(320) not null,
  author_role text not null check (author_role in ('admin', 'worker', 'volunteer')),
  status text not null default 'pending_admin_approval' check (status in ('draft', 'pending_admin_approval', 'approved', 'rejected', 'published')),
  rejection_reason text,
  approved_by varchar(320),
  approved_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.news_approval_events (
  id uuid primary key default gen_random_uuid(),
  news_id uuid not null references public.news_articles(id) on delete cascade,
  action text not null check (action in ('submitted', 'approved', 'rejected', 'published')),
  actor_email varchar(320) not null,
  actor_role text not null check (actor_role in ('admin', 'worker', 'volunteer')),
  reason text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists news_articles_status_published_idx
  on public.news_articles (status, published_at desc);
create index if not exists news_articles_created_idx
  on public.news_articles (created_at desc);
create index if not exists news_articles_author_created_idx
  on public.news_articles (author_email, created_at desc);
create index if not exists news_approval_events_news_created_idx
  on public.news_approval_events (news_id, created_at desc);

alter table public.news_articles enable row level security;
alter table public.news_approval_events enable row level security;

drop policy if exists "Service role can manage news articles" on public.news_articles;
create policy "Service role can manage news articles"
  on public.news_articles for all to service_role using (true) with check (true);

drop policy if exists "Service role can manage news approval events" on public.news_approval_events;
create policy "Service role can manage news approval events"
  on public.news_approval_events for all to service_role using (true) with check (true);

create or replace function public.touch_news_article_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists news_articles_updated_at on public.news_articles;
create trigger news_articles_updated_at
before update on public.news_articles
for each row execute function public.touch_news_article_updated_at();
