-- HMSI Supabase schema
-- Run this once in the Supabase SQL editor before enabling submissions.

create extension if not exists pgcrypto;

create table if not exists public.fundraisers (
  id text primary key,
  title varchar(160) not null,
  description text not null,
  category text not null check (category in ('medical', 'education', 'housing', 'emergency')),
  target_amount numeric(14, 2) not null check (target_amount > 0),
  raised_amount numeric(14, 2) not null default 0 check (raised_amount >= 0),
  image_url text not null,
  image_path text,
  status text not null default 'active' check (status in ('active', 'pending', 'archived')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists fundraisers_status_created_at_idx
  on public.fundraisers (status, created_at desc);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name varchar(160) not null,
  email varchar(320) not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'resolved')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.signup_requests (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  email varchar(320) not null,
  phone varchar(64),
  message text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.fundraisers enable row level security;
alter table public.contact_messages enable row level security;
alter table public.signup_requests enable row level security;

drop policy if exists "Anyone can view active fundraisers" on public.fundraisers;
create policy "Anyone can view active fundraisers"
  on public.fundraisers for select
  using (status = 'active');

-- Inserts and updates are intentionally service-role-only through the server API.

drop policy if exists "Public can read fundraiser images" on storage.objects;
create policy "Public can read fundraiser images"
  on storage.objects for select
  using (bucket_id = 'fundraiser-images');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fundraiser-images',
  'fundraiser-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into public.fundraisers (id, title, description, category, target_amount, raised_amount, image_url, status, created_at)
values
  ('f1', 'Emergency Medical Surgery for Baby Tobi', 'Baby Tobi needs urgent heart surgery. Every donation counts.', 'medical', 2500000, 750000, '/images/outreach-2.png', 'active', '2026-08-01T10:00:00Z'),
  ('f2', 'Rebuilding Makoko Primary School', 'Help us fix the roof and provide desks for 200 students.', 'education', 5000000, 1200000, '/images/outreach-5.png', 'active', '2026-08-10T14:30:00Z')
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  target_amount = excluded.target_amount,
  raised_amount = excluded.raised_amount,
  image_url = excluded.image_url,
  status = excluded.status,
  updated_at = timezone('utc', now());


-- Admin workflow tables
create table if not exists public.volunteer_applications (
  id uuid primary key default gen_random_uuid(),
  name varchar(160) not null,
  email varchar(320) not null,
  phone varchar(64) not null,
  interest varchar(160) not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workers (
  id uuid primary key default gen_random_uuid(),
  name varchar(160) not null,
  email varchar(320) not null unique,
  phone varchar(64) not null,
  role text not null default 'worker' check (role in ('worker', 'coordinator')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.work_assignments (
  id uuid primary key default gen_random_uuid(),
  title varchar(200) not null,
  description text not null,
  kind text not null check (kind in ('assistance', 'job')),
  status text not null default 'assigned' check (status in ('assigned', 'in_progress', 'completed')),
  assigned_worker_id uuid not null references public.workers(id) on delete restrict,
  fundraiser_id text references public.fundraisers(id) on delete set null,
  due_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists volunteer_applications_status_created_at_idx
  on public.volunteer_applications (status, created_at desc);
create index if not exists work_assignments_worker_status_idx
  on public.work_assignments (assigned_worker_id, status);

alter table public.volunteer_applications enable row level security;
alter table public.workers enable row level security;
alter table public.work_assignments enable row level security;

-- The server admin API uses the service-role key. No anonymous write policy is granted.
-- Public fundraiser visibility remains limited to active records.
alter table public.fundraisers drop constraint if exists fundraisers_status_check;
alter table public.fundraisers add constraint fundraisers_status_check
  check (status in ('active', 'pending', 'archived', 'rejected'));


-- Public submission policies. New records are constrained to review-safe statuses;
-- admin-only updates, approvals, workers, and assignments remain service-role-only.
drop policy if exists "Public can submit pending fundraisers" on public.fundraisers;
create policy "Public can submit pending fundraisers"
  on public.fundraisers for insert
  with check (status = 'pending' and raised_amount = 0);

drop policy if exists "Public can submit contact messages" on public.contact_messages;
create policy "Public can submit contact messages"
  on public.contact_messages for insert
  with check (status = 'new');

drop policy if exists "Public can submit signup requests" on public.signup_requests;
create policy "Public can submit signup requests"
  on public.signup_requests for insert
  with check (true);

drop policy if exists "Public can submit volunteer applications" on public.volunteer_applications;
create policy "Public can submit volunteer applications"
  on public.volunteer_applications for insert
  with check (status = 'pending');


-- Role-aware applications, opportunities, and collaboration rooms
alter table public.volunteer_applications add column if not exists applicant_role text not null default 'volunteer';
alter table public.volunteer_applications drop constraint if exists volunteer_applications_applicant_role_check;
alter table public.volunteer_applications add constraint volunteer_applications_applicant_role_check
  check (applicant_role in ('volunteer', 'worker'));

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  title varchar(200) not null,
  description text not null,
  audience text not null default 'volunteer' check (audience in ('volunteer', 'worker', 'both')),
  location varchar(200) not null default 'Nigeria and Africa',
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'open' check (status in ('draft', 'open', 'closed')),
  created_by varchar(320),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.opportunity_applications (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities(id) on delete cascade,
  applicant_name varchar(160) not null,
  applicant_email varchar(320) not null,
  applicant_phone varchar(64) not null,
  applicant_role text not null check (applicant_role in ('volunteer', 'worker')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  unique (opportunity_id, applicant_email)
);

create table if not exists public.community_posts (
  id uuid primary key default gen_random_uuid(),
  audience text not null default 'volunteer' check (audience in ('volunteer', 'worker', 'all')),
  author_name varchar(160) not null,
  author_role text not null check (author_role in ('volunteer', 'worker', 'admin')),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.community_posts(id) on delete cascade,
  author_name varchar(160) not null,
  author_role text not null check (author_role in ('volunteer', 'worker', 'admin')),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.community_likes (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.community_posts(id) on delete cascade,
  actor_key varchar(320) not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (post_id, actor_key)
);

create index if not exists opportunities_status_starts_at_idx on public.opportunities (status, starts_at);
create index if not exists opportunity_applications_status_created_at_idx on public.opportunity_applications (status, created_at desc);
create index if not exists community_posts_audience_created_at_idx on public.community_posts (audience, created_at desc);
create index if not exists community_comments_post_created_at_idx on public.community_comments (post_id, created_at);
create index if not exists community_likes_post_idx on public.community_likes (post_id);

alter table public.opportunities enable row level security;
alter table public.opportunity_applications enable row level security;
alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_likes enable row level security;

drop policy if exists "Public can view open opportunities" on public.opportunities;
create policy "Public can view open opportunities" on public.opportunities for select using (status = 'open');

drop policy if exists "Public can submit opportunity applications" on public.opportunity_applications;
create policy "Public can submit opportunity applications" on public.opportunity_applications for insert with check (status = 'pending');

drop policy if exists "Public can view collaboration posts" on public.community_posts;
create policy "Public can view collaboration posts" on public.community_posts for select using (true);

drop policy if exists "Public can create collaboration posts" on public.community_posts;
create policy "Public can create collaboration posts" on public.community_posts for insert with check (audience in ('volunteer', 'worker', 'all'));

drop policy if exists "Public can view collaboration comments" on public.community_comments;
create policy "Public can view collaboration comments" on public.community_comments for select using (true);

drop policy if exists "Public can create collaboration comments" on public.community_comments;
create policy "Public can create collaboration comments" on public.community_comments for insert with check (true);

drop policy if exists "Public can view collaboration likes" on public.community_likes;
create policy "Public can view collaboration likes" on public.community_likes for select using (true);

drop policy if exists "Public can create collaboration likes" on public.community_likes;
create policy "Public can create collaboration likes" on public.community_likes for insert with check (true);

drop policy if exists "Public can remove collaboration likes" on public.community_likes;
create policy "Public can remove collaboration likes" on public.community_likes for delete using (true);
