-- HMSI first-party traffic analytics
-- Run this migration in the Supabase SQL Editor before using the admin Traffic analytics view.
-- No IP address, email address, full user-agent, query string, or beneficiary data is stored.

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  event_type text not null default 'page_view' check (event_type in ('page_view', 'link_click')),
  path text not null,
  target_path text,
  referrer_host varchar(180),
  utm_source varchar(100),
  utm_medium varchar(100),
  utm_campaign varchar(160),
  created_at timestamptz not null default timezone('utc', now()),
  check (path like '/%' and path not like '//%'),
  check (target_path is null or (target_path like '/%' and target_path not like '//%'))
);

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);
create index if not exists page_views_event_path_idx
  on public.page_views (event_type, path);
create index if not exists page_views_event_target_idx
  on public.page_views (event_type, target_path);
create index if not exists page_views_source_idx
  on public.page_views (utm_source, utm_medium, referrer_host);

alter table public.page_views enable row level security;

drop policy if exists "Service role can manage page views" on public.page_views;
create policy "Service role can manage page views"
  on public.page_views for all to service_role
  using (true) with check (true);

comment on table public.page_views is 'Privacy-safe first-party HMSI traffic events. Store aggregate reporting inputs only; never store IPs, emails, or raw query strings.';
comment on column public.page_views.referrer_host is 'Hostname only, not a full referrer URL.';
comment on column public.page_views.target_path is 'Same-site destination pathname for internal link-click reporting.';
