'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BadgeCheck, Search } from 'lucide-react';
export default function SchoolCertificateVerifyPage() {
  const [number, setNumber] = useState(''); const [code, setCode] = useState(''); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setResult(null); setBusy(true); try { const response = await fetch('/api/school/certificates/verify-public', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ certificate_number: number, verification_code: code }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'The certificate could not be verified.'); setResult(payload.certificate); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The certificate could not be verified.'); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#f6f4ef] px-5 py-12 text-[#17221e] sm:px-8"><div className="mx-auto max-w-xl"><Link href="/school" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#1e5b49]"><ArrowLeft size={15} /> Back to school</Link><section className="mt-8 rounded-3xl border border-[#d9d6ce] bg-white p-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e9f0e9] text-[#1e5b49]"><Search size={23} /></div><p className="mt-6 text-xs font-black uppercase tracking-widest text-[#b56b3b]">HMSI verification</p><h1 className="mt-2 text-3xl font-black">Verify a school certificate</h1><p className="mt-3 text-sm leading-6 text-[#66716a]">Verification requires both the certificate number and the private code supplied to the certificate holder.</p><form onSubmit={submit} className="mt-6 space-y-4"><input required value={number} onChange={(event) => setNumber(event.target.value.toUpperCase())} placeholder="HMSI-HS-2026-XXXXXXXX" className="w-full rounded-2xl bg-[#f6f4ef] px-4 py-3 font-mono text-sm uppercase outline-none focus:ring-2 focus:ring-[#1e5b49]" /><input required value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="Private verification code" className="w-full rounded-2xl bg-[#f6f4ef] px-4 py-3 font-mono text-sm uppercase tracking-widest outline-none focus:ring-2 focus:ring-[#1e5b49]" /><button disabled={busy} className="w-full rounded-full bg-[#1e5b49] py-3 text-xs font-black uppercase tracking-widest text-white disabled:opacity-50">{busy ? 'Checking…' : 'Verify certificate'}</button></form>{error && <p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{result && <div className="mt-6 rounded-2xl bg-[#e9f0e9] p-5"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#1e5b49]"><BadgeCheck size={17} /> Valid HMSI certificate</p><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold text-[#66716a]">Holder</dt><dd className="font-black">{result.holder_name}</dd></div><div><dt className="font-bold text-[#66716a]">Credential</dt><dd>{result.certificate_title}</dd></div><div><dt className="font-bold text-[#66716a]">Issued</dt><dd>{result.issued_on}</dd></div><div><dt className="font-bold text-[#66716a]">Number</dt><dd className="font-mono">{result.certificate_number}</dd></div></dl><p className="mt-4 border-t border-[#c9ddcf] pt-4 text-xs leading-5 text-[#66716a]">{result.notice}</p></div>}</section></div></main>;
}
