'use client';

import { useEffect, useState } from 'react';
import { BadgeCheck, Printer, ShieldCheck } from 'lucide-react';

type Card = { member_number: string; holder_role: 'worker' | 'volunteer'; holder_name: string; holder_email: string; role_display: string; activated_at?: string | null; status: string; expires_at?: string | null };

export function PrintableHmsiIdCard({ card, activationCode }: { card: Card; activationCode?: string }) {
  return <div className="hmsi-id-card-printable relative w-full max-w-[560px] overflow-hidden rounded-[28px] border-2 border-[#1e5b49] bg-white text-[#17221e] shadow-xl"><div className="flex items-center justify-between bg-[#17221e] px-6 py-4 text-white"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-[#e1ad45]">Help Meet Shine Initiative</p><p className="mt-1 text-lg font-black">HMSI MEMBER ID</p></div><ShieldCheck className="text-[#e1ad45]" size={30} /></div><div className="grid grid-cols-[1fr_145px] gap-5 p-6"><div className="space-y-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#66716a]">Name</p><p className="text-xl font-black">{card.holder_name}</p></div><div className="grid grid-cols-2 gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#66716a]">Role</p><p className="text-sm font-black">{card.role_display}</p></div><div><p className="text-[10px] font-black uppercase tracking-widest text-[#66716a]">Member no.</p><p className="text-sm font-black">{card.member_number}</p></div></div><div><p className="text-[10px] font-black uppercase tracking-widest text-[#66716a]">Status</p><p className="inline-flex items-center gap-1 text-sm font-black text-[#1e5b49]"><BadgeCheck size={15} /> {card.status === 'active' ? 'Active' : card.status}</p></div>{card.expires_at && <p className="text-[10px] font-bold uppercase tracking-widest text-[#66716a]">Card expiry: {card.expires_at}</p>}{activationCode && <div className="rounded-2xl border border-[#e1ad45] bg-[#fff8e8] p-3"><p className="text-[10px] font-black uppercase tracking-widest text-[#7a5b16]">Temporary activation code</p><p className="mt-1 font-mono text-lg font-black tracking-[0.18em] text-[#17221e]">{activationCode}</p><p className="mt-1 text-[10px] leading-4 text-[#7a5b16]">Use once with the member number. Do not publish this code online.</p></div>}</div><div className="flex flex-col items-center justify-center rounded-2xl bg-[#e9f0e9] p-3 text-center"><div className="flex h-24 w-24 items-center justify-center rounded-xl border-2 border-dashed border-[#1e5b49] bg-white text-[9px] font-black uppercase tracking-widest text-[#1e5b49]">Verify<br />HMSI ID</div><p className="mt-3 text-[10px] font-bold leading-4 text-[#66716a]">Verify through the HMSI member portal.</p></div></div><div className="border-t border-[#d9d6ce] px-6 py-3 text-[10px] leading-4 text-[#66716a]">This card identifies the named HMSI worker or volunteer. It is not a government identity document, professional licence, or proof of legal accreditation. Report a lost card to HMSI so it can be revoked.</div></div>;
}

export default function HmsiIdCardPanel() {
  const [card, setCard] = useState<Card | null>(null);
  const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/member/session', { cache: 'no-store' }).then((response) => response.json()).then((result) => { if (result.authenticated) setCard(result.member); }).catch(() => undefined); }, []);
  if (!card) return <div className="rounded-3xl border border-dashed border-[#d9d6ce] bg-white p-5"><p className="text-xs font-black uppercase tracking-widest text-[#b56b3b]">HMSI member ID</p><p className="mt-2 text-sm leading-6 text-[#66716a]">No activated HMSI ID card is linked to this session. Ask an administrator to issue or activate your approved worker or volunteer card.</p></div>;
  return <section className="space-y-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-[#b56b3b]">Your HMSI ID card</p><p className="mt-1 text-sm text-[#66716a]">The activation code is hidden after first use.</p></div><button type="button" onClick={() => { setMessage('Use your browser print dialog and select the card area.'); window.print(); }} className="inline-flex items-center gap-2 rounded-full bg-[#17221e] px-4 py-2 text-xs font-black uppercase tracking-widest text-white"><Printer size={14} /> Print</button></div>{message && <p className="text-xs text-[#1e5b49]">{message}</p>}<PrintableHmsiIdCard card={card} /></section>;
}
