'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, MapPin } from 'lucide-react';
type Opportunity = { id: string; title: string; description: string; audience: string; location: string; starts_at: string };
export default function HomepageVolunteerOpportunities() {
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [loaded, setLoaded] = useState(false);
  useEffect(() => { fetch('/api/opportunities', { cache: 'no-store' }).then((response) => response.ok ? response.json() : { opportunities: [] }).then((result) => { setOpportunities((result.opportunities || []).filter((item: Opportunity) => item.audience === 'volunteer' || item.audience === 'both').slice(0, 6)); setLoaded(true); }).catch(() => setLoaded(true)); }, []);
  if (loaded && opportunities.length === 0) return <section className="border-y border-[#d9d6ce] bg-[#e9f0e9] py-20"><div className="mx-auto max-w-[1440px] px-5 text-center sm:px-8 lg:px-12"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#b56b3b]">Volunteer with HMSI</p><h2 className="mt-3 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Bring your skills to community service.</h2><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-[#66716a]">Volunteer opportunities are reviewed and published by HMSI as programme needs are confirmed. Register your interest to be considered for a suitable role.</p><Link href="/volunteer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#1e5b49] px-5 py-3 text-xs font-black uppercase tracking-widest text-white">Explore volunteering <ArrowRight size={15} /></Link></div></section>;
  return <section id="volunteer-opportunities" className="border-y border-[#d9d6ce] bg-[#e9f0e9] py-20"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-[#b56b3b]">Open now · volunteer opportunities</p><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-0.04em] sm:text-5xl">Help HMSI start and strengthen safe operations.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#66716a]">Choose a role that matches your skills. Applications are free, reviewed by an administrator, and do not guarantee placement, employment, payment, or a stipend.</p></div><Link href="/opportunities" className="inline-flex items-center gap-2 text-sm font-black uppercase tracking-widest text-[#1e5b49]">See all opportunities <ArrowRight size={16} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{opportunities.map((opportunity) => <article key={opportunity.id} className="flex flex-col rounded-3xl border border-[#cbd9cf] bg-white p-6"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-[#f6f4ef] p-3 text-[#1e5b49]"><BriefcaseBusiness size={20} /></span><span className="text-[10px] font-black uppercase tracking-widest text-[#b56b3b]">Volunteer</span></div><h3 className="mt-5 text-xl font-black leading-tight">{opportunity.title}</h3><p className="mt-3 line-clamp-4 text-sm leading-6 text-[#66716a]">{opportunity.description}</p><p className="mt-4 flex items-center gap-2 text-xs font-bold text-[#66716a]"><MapPin size={14} /> {opportunity.location}</p><Link href={`/opportunities#opportunity-${opportunity.id}`} className="mt-6 inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#1e5b49]">Apply easily <ArrowRight size={14} /></Link></article>)}</div></div></section>;
}
