'use client';
import { useEffect, useState } from 'react';

export default function ModerationPanel() {
  const [data, setData] = useState<any>({ flags: [], workers: [], volunteers: [] });
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const load = async () => {
    const [moderation, overview] = await Promise.all([fetch('/api/admin/moderation', { cache: 'no-store' }), fetch('/api/admin/overview', { cache: 'no-store' })]);
    const m = await moderation.json(); const o = await overview.json();
    if (!moderation.ok) throw new Error(m.error || 'Moderation is unavailable.');
    setData({ flags: m.flags || [], workers: o.workers || [], volunteers: o.volunteers || [] });
  };
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const action = async (body: any) => { setError(''); setNotice(''); const r = await fetch(body.action === 'delete_comment' ? '/api/admin/moderation' : body.kind === 'worker' ? `/api/admin/workers/${body.id}` : `/api/admin/volunteers/${body.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body.action ? body : { status: body.status, ...(body.kind === 'volunteer' ? { accessStatus: body.status === 'banned' ? 'banned' : 'active' } : {}) }) }); const j = await r.json(); if (!r.ok) return setError(j.error || 'Action failed.'); setNotice('Moderation action completed.'); load().catch(() => undefined); };
  return <div className="space-y-6"><div><h2 className="text-2xl font-black">Moderation and access</h2><p className="mt-2 text-sm text-[#66716a]">Delete harmful comments, review worker flags, and suspend or restore access.</p></div>{(error || notice) && <p className="rounded-2xl bg-[#f6f4ef] p-4 text-sm">{error || notice}</p>}<section className="rounded-3xl border border-[#d9d6ce] bg-white p-6"><h3 className="text-lg font-black">Flagged comments</h3>{data.flags.length === 0 ? <p className="mt-3 text-sm text-[#66716a]">No comment flags.</p> : data.flags.map((flag: any) => <div key={flag.id} className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#f6f4ef] p-4"><div><p className="text-sm font-black">{flag.reason}</p><p className="text-xs text-[#66716a]">Reported by {flag.reporter_role} · {flag.status}</p></div><div className="flex gap-2"><button onClick={() => action({ action: 'delete_comment', commentId: flag.comment_id })} className="rounded-full bg-red-600 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-white">Delete comment</button><button onClick={() => action({ flagId: flag.id, status: 'dismissed' })} className="rounded-full border px-3 py-2 text-[10px] font-black uppercase tracking-widest">Dismiss</button></div></div>)}</section><section className="grid gap-6 md:grid-cols-2"><div className="rounded-3xl border border-[#d9d6ce] bg-white p-6"><h3 className="text-lg font-black">Workers</h3>{data.workers.map((w: any) => <div key={w.id} className="mt-3 flex items-center justify-between gap-2 text-sm"><span>{w.name} <small className="text-[#66716a]">({w.status})</small></span><button onClick={() => action({ kind: 'worker', id: w.id, status: w.status === 'active' ? 'inactive' : 'active' })} className="rounded-full border px-3 py-1 text-[10px] font-black uppercase">{w.status === 'active' ? 'Ban' : 'Restore'}</button></div>)}</div><div className="rounded-3xl border border-[#d9d6ce] bg-white p-6"><h3 className="text-lg font-black">Volunteers</h3>{data.volunteers.filter((v: any) => v.status === 'approved').map((v: any) => <div key={v.id} className="mt-3 flex items-center justify-between gap-2 text-sm"><span>{v.name} <small className="text-[#66716a]">({v.account_status || 'active'})</small></span><button onClick={() => action({ kind: 'volunteer', id: v.id, status: v.account_status === 'banned' ? 'active' : 'banned' })} className="rounded-full border px-3 py-1 text-[10px] font-black uppercase">{v.account_status === 'banned' ? 'Restore' : 'Ban'}</button></div>)}</div></section></div>;
}
