import { NextResponse } from 'next/server';
import { getAdminEmailFromCookie } from '../../../../lib/adminSession';
import { getSupabaseAdmin } from '../../../../lib/supabaseAdmin';
export const runtime = 'nodejs';
function error(message: string, status = 400) { return NextResponse.json({ error: message }, { status }); }
function hasSameOrigin(request: Request) { const origin = request.headers.get('origin'); if (!origin) return false; try { return new URL(origin).host === new URL(request.url).host; } catch { return false; } }
export async function GET(request: Request) { const adminEmail = getAdminEmailFromCookie(request.headers.get('cookie')); if (!adminEmail) return error('Admin authentication required.', 401); const admin = getSupabaseAdmin(); if (!admin) return error('Member tasks are unavailable.', 503); const result = await admin.from('hmsi_member_tasks').select('id,assigned_member_id,title,description,kind,priority,status,due_at,completion_note,submitted_at,reviewed_at,reviewed_by,review_note,created_by,created_at,updated_at,completed_at').eq('is_deleted', false).order('created_at', { ascending: false }).limit(500); if (result.error) return error('Member tasks are unavailable. Apply the HMSI governance foundation migration first.', 503); return NextResponse.json({ tasks: result.data || [] }); }
export async function POST(request: Request) { if (!hasSameOrigin(request)) return error('Cross-site member-task changes are not allowed.', 403); const adminEmail = getAdminEmailFromCookie(request.headers.get('cookie')); if (!adminEmail) return error('Admin authentication required.', 401); const admin = getSupabaseAdmin(); if (!admin) return error('Member tasks are unavailable.', 503); const body = await request.json().catch(() => ({})); const memberId = typeof body.assigned_member_id === 'string' ? body.assigned_member_id.trim() : ''; const title = typeof body.title === 'string' ? body.title.trim().slice(0, 220) : ''; const description = typeof body.description === 'string' ? body.description.trim().slice(0, 5000) : ''; const kind = typeof body.kind === 'string' ? body.kind.trim().slice(0, 40) : 'member_support'; const priority = ['low', 'normal', 'high', 'urgent'].includes(body.priority) ? body.priority : 'normal'; const dueAt = typeof body.due_at === 'string' && !Number.isNaN(Date.parse(body.due_at)) ? body.due_at : null; if (!memberId || title.length < 3 || description.length < 10) return error('An active member, task title, and description are required.'); const member = await admin.from('hmsi_members').select('id').eq('id', memberId).eq('status', 'active').maybeSingle(); if (member.error || !member.data) return error('Only active approved members may receive tasks.', 403); const task = await admin.from('hmsi_member_tasks').insert({ assigned_member_id: memberId, title, description, kind, priority, due_at: dueAt, created_by: adminEmail }).select('id,assigned_member_id,title,description,kind,priority,status,due_at,created_by,created_at').single(); if (task.error || !task.data) return error('The member task could not be created.', 503); await admin.from('hmsi_member_task_events').insert({ task_id: task.data.id, actor_email: adminEmail, actor_role: 'admin', action: 'assigned', note: null }); return NextResponse.json({ task: task.data, message: 'Task assigned to the member.' }, { status: 201 }); }
export async function PATCH(request: Request) { if (!hasSameOrigin(request)) return error('Cross-site member-task changes are not allowed.', 403); const adminEmail = getAdminEmailFromCookie(request.headers.get('cookie')); if (!adminEmail) return error('Admin authentication required.', 401); const admin = getSupabaseAdmin(); if (!admin) return error('Member tasks are unavailable.', 503); const body = await request.json().catch(() => ({})); const id = typeof body.id === 'string' ? body.id.trim() : ''; const status = body.status === 'completed' || body.status === 'cancelled' ? body.status : ''; const note = typeof body.review_note === 'string' ? body.review_note.trim().slice(0, 4000) : ''; if (!id || !status || !note) return error('A submitted member task, review decision, and review note are required.'); const now = new Date().toISOString(); const task = await admin.from('hmsi_member_tasks').update({ status, review_note: note, reviewed_at: now, reviewed_by: adminEmail, completed_at: status === 'completed' ? now : null, updated_at: now }).eq('id', id).eq('status', 'submitted').eq('is_deleted', false).select('id,assigned_member_id,status,completion_note,review_note,reviewed_at,reviewed_by,completed_at').maybeSingle(); if (task.error || !task.data) return error('Only a current submitted member task can be reviewed.', 409); await admin.from('hmsi_member_task_events').insert({ task_id: id, actor_email: adminEmail, actor_role: 'admin', action: `review_${status}`, note }); return NextResponse.json({ task: task.data }); }
