'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BadgeCheck, CreditCard, Loader2 } from 'lucide-react';

type RequestRecord = { id: string; certificate_title: string; amount_ngn: number; status: string; created_at: string };
export default function SchoolCertificatesPage() {
  const [requests, setRequests] = useState<RequestRecord[]>([]);
  const [error, setError] = useState('');
  const [busyId, setBusyId] = useState('');
  useEffect(() => { fetch('/api/member/certificates', { cache: 'no-store' }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Certificate requests are unavailable.'); setRequests(result.requests || []); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Certificate requests are unavailable.')); }, []);
  const pay = async (requestId: string) => { setBusyId(requestId); setError(''); try { const response = await fetch('/api/school/certificates/initialize', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ request_id: requestId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Payment could not be initialized.'); window.location.assign(result.authorization_url); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Payment could not be initialized.'); setBusyId(''); } };
  return <main className="min-h-screen bg-[#f6f4ef] px-5 py-12 text-[#17221e] sm:px-8"><div className="mx-auto max-w-3xl"><Link href="/school" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#1e5b49]"><ArrowLeft size={15} /> Back to school</Link><div className="mt-8 rounded-3xl bg-[#17221e] p-7 text-white"><p className="text-xs font-black uppercase tracking-widest text-[#e1ad45]">HMSI school credentials</p><h1 className="mt-3 text-3xl font-black">Certificate requests</h1><p className="mt-3 text-sm leading-6 text-white/70">Only an administrator can mark your learning pathway complete and create a certificate request. Payment is verified through Paystack; issuance remains a separate administrator step.</p></div>{error && <p className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-4">{requests.length === 0 ? <div className="rounded-3xl border border-dashed border-[#d9d6ce] bg-white p-10 text-center text-sm text-[#66716a]">No certificate requests are linked to this activated member session.</div> : requests.map((request) => <article key={request.id} className="rounded-3xl border border-[#d9d6ce] bg-white p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-[#1e5b49]"><BadgeCheck size={18} /><p className="text-xs font-black uppercase tracking-widest">{request.status}</p></div><h2 className="mt-3 text-lg font-black">{request.certificate_title}</h2><p className="mt-2 text-sm text-[#66716a]">Fee: ₦{Number(request.amount_ngn).toLocaleString('en-NG')} · Requested {new Date(request.created_at).toLocaleDateString()}</p></div>{['eligible', 'pending_payment'].includes(request.status) && <button disabled={busyId === request.id} onClick={() => pay(request.id)} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#1e5b49] px-5 py-3 text-xs font-black uppercase tracking-widest text-white disabled:opacity-50">{busyId === request.id ? <Loader2 size={14} className="animate-spin" /> : <CreditCard size={14} />} Pay with Paystack</button>}</div>{request.status === 'paid' && <p className="mt-4 rounded-2xl bg-[#e9f0e9] p-4 text-sm text-[#1e5b49]">Payment verified. HMSI administration still needs to issue the certificate.</p>}{request.status === 'issued' && <p className="mt-4 rounded-2xl bg-[#e9f0e9] p-4 text-sm text-[#1e5b49]">Certificate issued. Check your email for the printable PDF and private verification code.</p>}</article>)}</div></div></main>;
}
