'use client';

import Link from 'next/link';
import { FormEvent, Suspense, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

function SetupPasswordContent() {
  const search = useSearchParams(); const router = useRouter();
  const token = search.get('token') || ''; const id = (search.get('id') || '').toUpperCase();
  const [hmsiId, setHmsiId] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState('Preparing your secure setup link…'); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/setup-password?token=${encodeURIComponent(token)}&id=${encodeURIComponent(id)}`, { cache: 'no-store' }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || 'This setup link is invalid or expired.'); setHmsiId(data.hmsiId); setReady(true); setMessage('Choose a password for future HMSI portal sign-ins.'); }).catch((error) => setMessage(error instanceof Error ? error.message : 'This setup link is invalid or expired.')); }, [token, id]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!ready || password.length < 10 || password !== confirmation) return; setBusy(true); try { const response = await fetch('/api/setup-password', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, hmsiId, password, confirmPassword: confirmation }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Password setup could not be completed.'); router.replace(data.redirectTo || '/portal/my-tasks'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Password setup could not be completed.'); } finally { setBusy(false); } }
  const mismatch = confirmation.length > 0 && password !== confirmation;
  return <main className="min-h-screen bg-[#f6f4ef] px-6 py-16"><div className="mx-auto max-w-md rounded-3xl border border-[#d9d6ce] bg-white p-8 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#b56b3b]">HMSI portal activation</p><h1 className="mt-2 text-3xl font-black text-[#17221e]">Set your password</h1><p role="status" className="mt-3 text-sm leading-6 text-[#66716a]">{message}</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-xs font-black uppercase tracking-widest text-[#17221e]">HMSI ID<input disabled value={hmsiId || id} className="mt-2 w-full rounded-xl border border-[#d9d6ce] bg-[#f6f4ef] px-4 py-3 text-sm font-normal normal-case tracking-normal text-[#66716a]" /></label><label className="block text-xs font-black uppercase tracking-widest text-[#17221e]">Password<input required minLength={10} type="password" autoComplete="new-password" disabled={!ready || busy} value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-[#d9d6ce] bg-[#f6f4ef] px-4 py-3 text-sm font-normal normal-case tracking-normal text-[#17221e]" /></label><label className="block text-xs font-black uppercase tracking-widest text-[#17221e]">Confirm password<input required minLength={10} type="password" autoComplete="new-password" disabled={!ready || busy} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} aria-invalid={mismatch} className="mt-2 w-full rounded-xl border border-[#d9d6ce] bg-[#f6f4ef] px-4 py-3 text-sm font-normal normal-case tracking-normal text-[#17221e]" />{mismatch && <span className="mt-1 block text-xs font-normal normal-case tracking-normal text-red-700">Passwords do not match.</span>}</label><button disabled={!ready || busy || password.length < 10 || password !== confirmation} className="w-full rounded-full bg-[#1e5b49] py-3 text-xs font-black uppercase tracking-widest text-white disabled:opacity-50">{busy ? 'Saving secure access…' : 'Save password & launch workspace'}</button></form><Link href="/login" className="mt-6 inline-block text-sm font-bold text-[#1e5b49]">Return to sign in</Link></div></main>;
}

export default function SetupPasswordPage() {
  return <Suspense fallback={<main className="flex min-h-screen items-center justify-center bg-[#f6f4ef] text-sm text-[#66716a]">Preparing secure setup…</main>}><SetupPasswordContent /></Suspense>;
}
