'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { ArrowLeft, Send, ShieldCheck } from 'lucide-react';
export default function MemberApplyPage() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', purpose: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); setError(''); try { const response = await fetch('/api/members/apply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Registration could not be submitted.'); setMessage(result.message); setForm({ name: '', email: '', phone: '', purpose: '' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Registration could not be submitted.'); } finally { setBusy(false); } };
  return <main className="flex min-h-screen items-center justify-center bg-[#f6f4ef] px-5 py-10 text-[#17221e]"><section className="w-full max-w-2xl rounded-3xl border border-[#d9d6ce] bg-white p-7 sm:p-10"><Link href="/" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#1e5b49]"><ArrowLeft size={15} /> HMSI home</Link><div className="mt-7 flex items-start gap-4"><div className="rounded-2xl bg-[#e9f0e9] p-3 text-[#1e5b49]"><ShieldCheck size={24} /></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#b56b3b]">Join HMSI</p><h1 className="mt-1 text-3xl font-black">Request general membership</h1><p className="mt-2 text-sm leading-6 text-[#66716a]">Applications are reviewed by an HMSI administrator. Approved members receive access to the moderated member room and may receive allocated member tasks.</p></div></div>{(error || message) && <div className={`mt-6 rounded-2xl border p-4 text-sm ${error ? 'border-red-100 bg-red-50 text-red-700' : 'border-emerald-100 bg-emerald-50 text-emerald-700'}`}>{error || message}</div>}<form onSubmit={submit} className="mt-7 space-y-4"><input required minLength={2} placeholder="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="w-full rounded-2xl bg-[#f6f4ef] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#1e5b49]" /><input required type="email" placeholder="Email address" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="w-full rounded-2xl bg-[#f6f4ef] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#1e5b49]" /><input placeholder="Phone (optional)" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className="w-full rounded-2xl bg-[#f6f4ef] px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-[#1e5b49]" /><textarea required minLength={20} rows={5} placeholder="Why would you like to join HMSI? Please do not include sensitive beneficiary information." value={form.purpose} onChange={(event) => setForm({ ...form, purpose: event.target.value })} className="w-full resize-y rounded-2xl bg-[#f6f4ef] px-4 py-3 text-sm leading-6 outline-none focus:ring-2 focus:ring-[#1e5b49]" /><button disabled={busy} className="inline-flex items-center gap-2 rounded-full bg-[#1e5b49] px-5 py-3 text-xs font-black uppercase tracking-widest text-white disabled:opacity-50">{busy ? 'Submitting…' : 'Submit membership request'} <Send size={14} /></button></form><p className="mt-6 text-xs leading-5 text-[#66716a]">Membership is subject to HMSI review, safeguarding requirements, and the privacy notice. Approval does not guarantee paid work or a stipend.</p></section></main>;
}
